version: "3.9"
services:
  bank-service:
    depends_on:
      - bank-service-db
    build: .
    ports:
      - "8081:8081"
  bank-service-db:
    image: postgres:14.0
    environment:
      - POSTGRES_DB=XXX
      - POSTGRES_USER=XXX
      - POSTGRES_PASSWORD=XXX
    volumes:
      - bank-service-data:/var/lib/postgresql/data:rw
volumes:
  bank-service-data: